tour/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import *
from django.db import transaction
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()

# __________________________________________Tourist Register Form___________________________________________


class TouristForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    age = forms.CharField(max_length=4, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    contact_no = forms.CharField(
        max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', max_length=30,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Password Confirmation', max_length=30,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'username', 'age',
                  'contact_no', 'email', 'password1', 'password2']

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_tourist = True
        if commit:
            user.save()
        tourist = Tourist.objects.create(user=user, first_name=self.cleaned_data.get('first_name'), last_name=self.cleaned_data.get(
            'last_name'), age=self.cleaned_data.get('age'), contact_no=self.cleaned_data.get('contact_no'))
        return user

# __________________________________________Main admin Register Form___________________________________________


class adminForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Password', max_length=30,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Password Confirmation', max_length=30,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password1', 'password2']

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_mainadmin = False
        if commit:
            user.save()
        mainadmin = Mainadmin.objects.create(user=user,)
        return user



# _____________________________________profile form________________________________

class ProfileForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = Tourist
        fields = ['email','contact_no','age']
        widgets = {
            "contact_no": forms.NumberInput(attrs={'class': 'form-control'}),
            "age":forms.TextInput(attrs={'class': 'form-control'})

        }




# __________________________________________Login Form___________________________________________

class UserloginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password']


# __________________________________________Tourplace Form___________________________________________

class tourPlaceForm(forms.ModelForm):
    class Meta:
        model = TourPlaces
        fields = ['state', 'description', 'placeImage']
        labels = {'state': 'State', 'description': 'Description',
                  'placeImage': 'Image'}
        widgets = {
            "state": forms.Select(attrs={'class': 'form-select'}),
            "description": forms.Textarea(attrs={'class': 'form-control'}),
            "placeImage": forms.FileInput(attrs={'class': 'form-control'}),
        }





# _________________________________________Carousal Form___________________________________________

class CaroForm(forms.ModelForm):
    class Meta:
        model = CarouselM
        fields = ['t_place',]
        labels = {'t_place': 'Add Place to Carousel', }
        widgets = {
            "t_place": forms.Select(attrs={'class': 'form-select'}),
        }

# _________________________________________state Form___________________________________________

class StateForm(forms.ModelForm):
    class Meta:
        model = States
        fields = ['s_name',]
        labels = {'s_name': 'Add State', }
        widgets = {
            "s_name": forms.TextInput(attrs={'class': 'form-control'}),
        }

# _________________________________________state Form___________________________________________

class QualityForm(forms.ModelForm):
    class Meta:
        model = Quality
        fields = ['q_name',]
        labels = {'q_name': 'Add Quality', }
        widgets = {
            "q_name": forms.TextInput(attrs={'class': 'form-control'}),
        }


# ________________________________________TourMoreplaces form_______________________________________

class TourMorePlacesForm(forms.ModelForm):
    class Meta:
        model = TourMorePlaces
        fields = ['place_name','description','placeImage','source_link','category']
        labels = {'place_name': 'Place Name', 'description':'Description','placeImage':'Upload image','source_link':'Embed map link','category':'Select categories'}
        widgets = {
            "place_name": forms.TextInput(attrs={'class': 'form-control'}),
            "description": forms.Textarea(attrs={'class': 'form-control'}),
            "placeImage": forms.FileInput(attrs={'class': 'form-control'}),
            "source_link": forms.TextInput(attrs={'class': 'form-control'}),
            "category": forms.CheckboxSelectMultiple(attrs={'class': ''}),
        }





# __________________________________________package Form___________________________________________

class PackageForm(forms.ModelForm):

    class Meta:
        model = Packages
        fields = ['pack_name', 'pack_facility', 'pack_member', 'start_date', 'end_date', 'quality', 'pack_price']
        labels = {
            'pack_name': 'Pack Name', 
            'pack_facility': 'Include Facilities',
            'pack_member': 'Total seats',
            'start_date': 'Starting Date',
            'end_date': 'Ending Date',
            'quality': 'Quality type',
            'pack_price': 'Package Price'
        }
        widgets = {
            "pack_name": forms.TextInput(attrs={'class': 'form-control'}),
            "pack_facility": forms.Textarea(attrs={'class': 'form-control'}),
            "pack_member": forms.NumberInput(attrs={'class': 'form-control'}),
            "start_date": forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            "end_date": forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            "quality": forms.Select(attrs={'class': 'form-select'}),
            "pack_price": forms.NumberInput(attrs={'class': 'form-control'}),
        }






# __________________________________________tour booking Form___________________________________________

class TourBookingForm(forms.ModelForm):
    class Meta:
        model = Tourbooking
        fields = ['contact', 'b_email', 'b_members']
        labels = {
            'contact': 'Contact', 
            'b_email': 'Email',
            'b_members': 'Members',
        }
        widgets = {
            "contact": forms.NumberInput(attrs={'class': 'form-control'}),
            "b_email": forms.EmailInput(attrs={'class': 'form-control'}),
            "b_members": forms.NumberInput(attrs={'class': 'form-control','oninput': 'calculateTotal(this.value)'}),
            
        }




# __________________________________________Review Form___________________________________________

class ReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(choices=[(x, x) for x in range(1, 6)], widget=forms.RadioSelect(attrs={"class": "form-control rating"}))

    class Meta:
        model = ReviewPack
        fields = ["r_des", "rating"]
        labels = {
            'r_des': 'Comments', 
        }

        widgets = {
            "r_des": forms.TextInput(attrs={"class": "form-control comment"}),
        }

templates/addpackage.html
{% extends 'base.html' %}

{% load static %}
{% block title %}AddPackage{% endblock %}
{% block content %}
<div class="text-center">
    <h1 class="text-light">
        Add Package
    </h1>
</div>
<div class="s-form">

    <div class="form-card container mb-3 p-3">
        <form action="" method="post" enctype="multipart/form-data" onsubmit="return vali(this);">
            {% csrf_token %}
            {{f.as_p}}
            <div id="errorMessages" style="color: rgb(153, 1, 1); padding: 10px;"></div>

            <input type="submit" value="Submit" class="btn btn-info text-white bg-opacity-50 ">
        </form>
    </div>
</div>


{% endblock %}


{% block js %}
<script>
    function vali(form) {
        var packMember = form.pack_member.value;
        var startDate = new Date(form.start_date.value);
        var endDate = new Date(form.end_date.value);
        var packPrice = form.pack_price.value;
        var errorMessages = "";

        if (packMember > 50) {
            errorMessages += "Package members cannot be greater than 50. \n";
        }

        var currentDate = new Date();
        if (startDate < currentDate) {
            errorMessages += "Start date cannot be earlier than the current date. \n";
        }

        if (endDate < startDate) {
            errorMessages += "End date cannot be earlier than the start date.  \n";
        }

        if (packPrice > 10000 || packPrice < 1000) {
            errorMessages += "Package price must be between 1000 and 10000.  \n";
        }

        if (errorMessages !== "") {
            document.getElementById("errorMessages").innerText = errorMessages;
            event.preventDefault();
            return false;
        } else {
            document.getElementById("errorMessages").innerText = "";
            return confirm('Do you really want to submit the form?');
        }
    }
</script>


{% endblock %}

templates/addplace.html
{% extends 'base.html' %}

{% load static %}
{% block title %}AddState{% endblock %}
{% block content %}
<div class="text-center">
    <h1 class="text-light">
        Add Place
    </h1>
</div>

    
    <div class="s-form">

    <div class="form-card container mb-3 p-3">
        <form action="" method="post" enctype="multipart/form-data" onsubmit="return check(this);">
            {% csrf_token %}
            {{f.as_p}}
            <input type="submit" value="Submit" class="btn btn-info text-white bg-opacity-50 ">
        </form>
    </div>
</div>

{% endblock %}

templates/addtour.html
{% extends 'base.html' %}

{% load static %}
{% block title %}AddTour{% endblock %}
{% block content %}
<div class="text-center">
    <h1 class="text-light">
        Add New tour
    </h1>

</div>
    <div class="s-form">
    <div class="form-card container mb-3 p-3">
        <form action="" method="post" enctype="multipart/form-data" onsubmit="return check(this);" onreset="return confirm_reset(this);">
            {% csrf_token %}
            {{f.as_p}}
            <input type="submit" value="Submit" class="btn btn-info text-white bg-opacity-50 ">
        <input type="reset" value="Reset" class="btn btn-sm btn-secondary bg-opacity-50 right">
        </form>
        


    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %}</title>

    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <link rel="stylesheet" href="{% static  'css/main.css' %}">
    <link rel="stylesheet" href="{% static  'css/flickity.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/footer.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
   
</head>

<body>
    
    {% include 'navbar.html' %}
    {% if messages %}
    {% for message in messages %}

    <div id='mssg' class=" container">

        <h6 {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</h6>
    </div>
    {% endfor %}
    {% endif %}
    {% block content %} {% endblock %}



    {% include 'footer.html' %}


    {% block js %} {% endblock %}
   

    <script src="{% static 'js/flickity.pkgd.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/sidenav.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js'%}"></script>
    <script src="{% static 'js/confirm.js'%}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>



</body>

</html>

templates/carousel.html
{% if k %}
<div class="gallery js-flickity" data-flickity-options='{ "wrapAround": true ,"autoPlay": 3000 , "pauseAutoPlayOnHover": false}'>
    {% for p in k %}
    <div class="gallery-cell">
        <a href="{% url 'tourview' p.t_place.id %}">
            <img src="{{ p.t_place.placeImage.url }}" alt="connect" srcset="">
            <div class="oc pt-2 text-center ">
                <p class="bg">{{p.t_place.state}}</p>
             </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/carouselview.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Carousel desk{% endblock %}
{% block content %}
<div class="text-center">
    <h1 class="text-light">
        Carousal View
    </h1>
</div>
{% include 'carousel.html' %}
<br>
<div class="row container">

    <div class="col-3 container">
        <div class="text-light s-form container bg-secondary bg-opacity-50  rounded py-2 my-4">
            <form action="{% url 'carousel' %}" method="post">
                {% csrf_token %}
                {{ f.as_p }}
                <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
    </div>

    <div class="col-9 container">
        <div class="main-tours">

        {% for p in ctp %}
        <div class="tour-card card bg-opacity-25 shadow mt-4">
            <div class="img-con">
                <img src="{{ p.t_place.placeImage.url }}" alt="connect" srcset="" class="shadow">
            </div>
            <P class="ps-2 pt-2 h6">{{p.t_place.state}}</P>
            <div class="o pt-2">
                <p class="bg">{{p.t_place.cities}}</p>
            </div>
            <a href="{% url 'carouseledit' p.id %}" class="btn edit btn-sm shadow btn-secondary">Replace</a>
        </div>
        {% endfor %}
    </div>
        
    </div>

</div>
{% endblock %}

templates/footer.html
<footer class="new_footer_area bg_color">
    <div class="new_footer_top">
        <div class="container">
                <div class="f_widget about-widget pl_70 wow fadeInLeft">
                    <h3 class="f-title f_600 t_color f_size_18">Info</h3>
                    <ul class="inline-list ">
                        <li><a href="{% url 'document' %}">Documentation</a></li>
                        <li><a href="{% url 't&c' %}">Term & conditions</a></li>
                        <li><a href="{% url 'privacy' %}">Privacy Policy</a></li>
                        <li><a href="{% url 'home' %}">Home</a></li>


                        
                    </ul>
                </div>
        </div>
        <div class="footer_bg">
            <div class="footer_bg_one"></div>
        </div>
    </div>
    <div class="footer_bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-7">
                    <p class="mb-0 f_400"> ©Copyrights Inc.. 2023 All rights reserved.</p>
                </div>
                <div class="col-lg-6 col-sm-5 text-right">
                    <p>Designed by <i class="icon_heart"></i><a href="https://github.com/MukeshVosheta/" target="_blank">MukeshSuthar</a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/login.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Sign-In{% endblock %}

{% block content %}

<div class="row m-4">

    <div class="col-8">
        <div class="logdis">
            <div class="logobg" id="backgif"></div>
            <div class="logbrand"></div>
        </div>
    </div>

    <div class="col-4 ">
        <div class="card shadow p-3 regi-form">
            <p class="text-center h3 fw-bold mb-5 mx-1 mx-md-4 mt-4 form-label text-secondary justify-content-center">
                Login</p>

            <form action="{% url 'Login' %}" method="post" class=" form">
                {% csrf_token %}
                {{ form.as_p }}

                        <button type="submit" class="btn btn-info text-white me-2">Login</button>
    
                    <p class="m-2 " >Not a member? <a href="{% url 'register' %}" class=" text-decoration-none">Register</a></p>
                
            </form>
        </div>
    </div>

</div>


{% endblock %}

templates/packageview.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Package{% endblock %}
{% block content %}

<div class="tourview">
    <img src="{{ tp.placeImage.url }}" alt="connect" srcset="">
    <P class="">{{tp.state}}</P>
</div>
<div class="details-2">
    <div class="t">
        <p class="v-title">State :</p>
        <P class="deta">{{tp.state}}</P>
    </div>
    <div class="t">
        <p class="v-title">Details:</p>
        <P class="deta">{{tp.description}}</P>
    </div>
</div>


<div class="row m-3">
    <div class="col-3 ">
        <div class="container rounded py-2">
            <div class="text-center">
                <h2 class="text-light">Book Now</h2>
            </div>
            <div class="form-card book-card container mb-3 p-3">
                <form action="{% url 'booktour' pack.id %}" method="post" enctype="multipart/form-data"
                    onsubmit="return check(this);">
                    {% csrf_token %}
                    {{f.as_p}}
                    <div>
                        <h5 class="total-price">Total Price :
                            <span id="totalPrice"></span> Rs
                        </h5>
                    </div>
                    <input type="submit" value="Book" class="btn btn-info text-light bg-opacity-50 book-btn">
                </form>
            </div>
        </div>
    </div>

    <div class="col-9 ">
        <div class="text-center">
            <h1 class="text-light">
                {{ pack.quality }}
            </h1>
        </div>
        <div class="bg-light rounded p-3 ">
            <h5>Facilities: {{pack.pack_facility}}</h5>
            <h5>Available Seats: {{pack.pack_member}}</h5>
            <h5>Price: Rs {{pack.pack_price}} per/person</h5>
            <h5>No extra Charges</h5>
            <h5>Start date: {{pack.start_date}}</h5>
            <h5>End date: {{pack.end_date}}</h5>
            <div class="pack-view-bt">
                <a href="{% url 'addwishlist' pack.id %}"> 
                    {% if added_wish %}
                    <button class="remove-wishlist">
                    Remove from Wishlist
                    </button>
                    {% else %}
                    <button class="add-wishlist">
                    Add to Wishlist 
                    </button>
                    {% endif %}
                    </strong></a>
            </div>
        </div>

    </div>

</div>


<div class="row my-5 ">



    <div class="container card-bg  rounded py-2">
        <div class="moretour">
            {% for i in mtp %}
            <div class="mt_sec">
                <div class="img">
                    <img src="{{ i.placeImage.url }}" alt="connect" srcset=""
                        onclick="openModal('{{ i.placeImage.url }}')">
                </div>
                <div class="content">
                    <div class="text-center">
                        <h2 class="title">
                            {{i.place_name}}
                        </h2>
                    </div>

                    <p class="paragraph">{{i.description}} </p>
                    <p class="cate"> category : <span class="cate-details">
                            {% for category in i.category.all %}
                            {{ category.c_name }}
                            {% endfor %}
                        </span>
                    </p>
                    {% if i.source_link %}
                    <iframe class="m-2 container" src="{{i.source_link}}" id="map" loading="lazy"></iframe>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>


    </div>

    {% if pack %}
    <div class="card-bg container  py-2 state-tours shadow mt-3 mb-3">
        {% for i in q_pack %}
        <div class="pack-card">
            <div class="pack-img"><a href="{% url 'packageview' i.id %}"><img src="{{ i.tourplace.placeImage.url }}"
                        alt="" class="" /></a></div>
            <div class="title text-center">
                <h4>{{i.pack_name}}</h4>
                <h6>{{i.tourplace}}</h6>
                <h6>{{i.quality}}</h6>
            </div>
            <div class="price">
                <a href="{% url 'packageview' i.id %}">
                    <h5><span>Rs </span>{{i.pack_price}}</h5>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>



<div class="row container">

    <div class="col-3">
        <div class="text-center">
            <h3 class="text-light">Give a feedback</h3>
        </div>
        <div class="form-card container mb-3 p-3 review-form">
            <form action="{% url 'addreview' pack.id %}" method="post" enctype="multipart/form-data"
                onsubmit="return check(this);">
                {% csrf_token %}
                <p>Add a Comment.</p>
                {{ r_form.r_des }}
                <div class="stars" id="stars">
                    <input type="radio" id="star5" name="star" value="5" class="star visually-hidden" /><label
                        for="star5">&#9733;</label>
                    <input type="radio" id="star4" name="star" value="4" class="star visually-hidden" /><label
                        for="star4">&#9733;</label>
                    <input type="radio" id="star3" name="star" value="3" class="star visually-hidden" /><label
                        for="star3">&#9733;</label>
                    <input type="radio" id="star2" name="star" value="2" class="star visually-hidden" /><label
                        for="star2">&#9733;</label>
                    <input type="radio" id="star1" name="star" value="1" class="star visually-hidden" /><label
                        for="star1">&#9733;</label>
                </div>
                <input type="hidden" id="id_rating" name="rating">
                <input type="submit" value="submit" class="btn btn-info text-light bg-opacity-50">
            </form>
        </div>
    </div>

    <div class="col-9">

        <!-- Review section -->
        {% if rating %}
        <div class="text-center">
            <h3 class="text-light">Reviews</h3>
        </div>
        <div class="container card-bg p-3">
            {% for r in rating %}
            <div class="review-card">
                <div class="d-flex justify-content-between position-static">
                    <h3 class="fs-5 ps-2">{{r.r_des}}</h3>
                    <div class="d-inline position-static star-bg">
                        <div class="blank-stars pe-3">{% for i in r.return_list %}<svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-star-fill text-warning" viewBox="0 0 16 16">
                                <path
                                    d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                            </svg>

                            {% endfor %}
                        </div>
                        <div class="filled-stars pe-3">{% for i in r.length %}

                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-star text-warning" viewBox="0 0 16 16">
                                <path
                                    d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z" />
                            </svg>

                            {% endfor %}
                        </div>
                    </div>
                </div>
                <p class="opacity-75 mt-2"><span class="r-title h6">Feed from: </span>{{r.r_user.username}}</p>
                <p class="opacity-75 rate-date mt-2">{{ r.r_upload_date }}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- end -->

    </div>

</div>











<div id="myModal" class="modal">
    <span class="close" onclick="closeModal()">&times;</span>
    <img class="modal-content" id="img01">
</div>

{% endblock %}

{% block js %}

<script>


    function validateForm(form) {
        var memberCount = document.getElementById("id_member_count").value;
        if (memberCount > 5) {
            alert("Only 5 members are allowed for the tour.");
            return false;
        }
        return true;
    }


    var price = "{{ pack.pack_price }}";
    function calculateTotal(members) {
        var pricePerPerson = price;
        var total = pricePerPerson * members;
        document.getElementById('totalPrice').innerText = total;
    }

    const stars = document.querySelectorAll(".star");

    stars.forEach((star) => {
        star.addEventListener("click", function () {
            const value = this.value;
            document.getElementById("id_rating").value = value;
        });
    });


</script>
{% endblock %}

templates/profileupdate.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="text-center">
    <h1 class="text-light my-5">
        Profile
    </h1>
</div>

<div class="row p-3 mb-5">

    <div class="col-6 container">
        <div class="Profile-card pro-card text-light">
            <h2 class=" title">Account Details</h2>
            <table class="profile-table">
                <tr>
                    <th>Name :</th>
                    <td>{{ t_user.first_name }}</td>
                </tr>
                <tr>
                    <th>Contact :</th>
                    <td>{{ t_user.contact_no }}</td>
                </tr>
                <tr>
                    <th>Email :</th>
                    <td>{{ t_email.email }}</td>
                </tr>
                <tr>
                    <th>age :</th>
                    <td>{{ t_user.age }}</td>
                </tr>
            </table>


            <input type="button" onclick="showdiv()" class=" pro-btn m-2 btn btn-info text-light" value="Change">
        </div>
    </div>




    <div class="col-4 container" id="profile-div">
        <div class="mb-5">
            <div class="form-card container mb-3 p-3">
                <div class="text-center mb-3 text-secondary">
                    <h4>Update Details </h4>
                </div>
                <form action="{% url 'profile' %}" method="post" enctype="multipart/form-data" onsubmit="return check(this);">
                    {% csrf_token %}
                    {{f.as_p}}
                    <input type="submit" value="Update" class="btn btn-info text-light bg-opacity-50 ">
                    <input type="button" onclick="divclose()" value="Cancel"
                        class="btn btn-warning text-light bg-opacity-50 ">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}
{% block js %}

<script>
    function showdiv() {
        document.getElementById('profile-div').style.display = "block";
    }
    function divclose() {
        document.getElementById('profile-div').style.display = "none"
    }

</script>

{% endblock %}

templates/updates.html
{% extends 'base.html' %}

{% block title %}Updates - Your Tour App{% endblock %}

{% block content %}
    <div class="container mt-5 mb-5">
        <div class="text-center text-light">
        <h2>Latest Updates</h2>
    </div>
        <div class="card p-3">
        <div class="update-card">
            <h3>Exciting New Destinations Added!</h3>
            <p class="update-date">Published on: November 15, 2023</p>
            <p>We are thrilled to announce that we have added new and exciting destinations to our list of tours. Explore these amazing places and create unforgettable memories with us!</p>
        </div>

        <div class="update-card">
            <h3>Upcoming Events</h3>
            <p class="update-date">Published on: November 10, 2023</p>
            <p>Don't miss out on our upcoming events! Join us for special tours, activities, and cultural experiences. Stay tuned for more details.</p>
        </div>
    </div>


    </div>
{% endblock %}